# This is a basic workflow to help you get started with Actions

name: BuildAndRunTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push, or pull request events but these only for the "main" branch
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    -  run: echo "Hello log!" 
    - uses: actions/checkout@v2

    - uses: microsoft/setup-msbuild@v1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore 

    - name: Build the application
      run: msbuild /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test    
        
        
        
